### ISSUE TITLE
show_inode.py crash

### ISSUE THREAD

**Issue by arvidjaar** [knorrie/python-btrfs#7]
v8

```
linux-gtrk:/host/home/src/python-btrfs/examples # ./show_inode.py 262 256 /
inode generation 15 transid 15874 size 24 nbytes 0 block_group 0 mode 40755 nlink 1 uid 0 gid 0 rdev 0 flags 0x0(none)
inode ref list size 1
    inode ref index 0 name utf-8 ..
Traceback (most recent call last):
  File "./show_inode.py", line 37, in <module>
    raise Exception("Whoa, key {}".format(btrfs.ctree.key_type_str(header.type)))
Exception: Whoa, key DIR_ITEM
```

**Comment by knorrie** [comment]
Ah, yeah, meh, it's actually modified version of the show_file example, which can only operate on files, not on directories. Since the purpose of the example code is to show how to get information about a file from the btrfs metadata if you only know an inode number and a tree (e.g. because you get them in some kernel error message), I renamed it to show_file_by_inode.py.

Also note that the main purpose of all of the scripts in examples, (even while they're sometimes quite useful in little day to day debugging sessions)... is to give examples how to work with the library, and to help others getting up to speed with doing whatever they want to do being able to dig around in the live metadata information that's available in a running Linux kernel.

Still, they should not spew out confusing messages when just trying them out. Thanks for testing and reporting this!
